export const supremeTitles: { [key: number]: string } = {
    1: "Knowledge",
    2: "Wisdom",
    3: "Understanding",
    4: "Culture/Freedom",
    5: "Power/Refinement",
    6: "Equality",
    7: "God",
    8: "Build/Destroy",
    9: "Born",
    10: "Cipher",
    11: "Knowledge Knowledge",
    12: "Knowledge Wisdom",
    13: "Knowledge Understanding",
    14: "Knowledge Culture/Freedom",
    15: "Knowledge Power/Refinement",
    16: "Knowledge Equality",
    17: "Knowledge God",
    18: "Knowledge Build/Destroy",
    19: "Knowledge Born",
    20: "Knowledge Cipher",
    21: "Wisdom Knowledge",
    22: "Wisdom Wisdom",
    23: "Wisdom Understanding",
    24: "Wisdom Culture/Freedom",
    25: "Wisdom Power/Refinement",
    26: "Wisdom Equality",
    27: "Wisdom God",
    28: "Wisdom Build/Destroy",
    29: "Wisdom Born",
    30: "Wisdom Cipher",
    31: "Understanding Knowledge",
};

export const supremeDescriptions: { [key: number]: string } = {
    1: "Represents awareness, learning, and perception.",
    2: "Symbolizes the manifestation of knowledge, applied wisdom, and insight.",
    3: "Reflects clear perception, comprehension, and mental clarity.",
    4: "Encompasses one's way of life and the pursuit of freedom.",
    5: "Signifies strength, refinement of character, and purity.",
    6: "Represents balance, fairness, and harmony in relationships.",
    7: "Acknowledges the divine presence within self.",
    8: "The process of creation and elimination of negativity.",
    9: "The completion and realization of potential.",
    10: "Signifies a cycle, circle, or state of wholeness.",
    11: "Further awareness, learning, and perception.",
    12: "The combined effort of learning and wise application.",
    13: "Awareness leading to clear comprehension.",
    14: "Awareness integrated into one's way of life.",
    15: "Awareness shaping strength and purity.",
    16: "Awareness fostering balance and fairness.",
    17: "Awareness of the divine presence within self.",
    18: "Awareness aiding the creation of positivity and removal of negativity.",
    19: "Awareness leading to the realization of potential.",
    20: "Awareness in the state of wholeness.",
    21: "Application of learned knowledge.",
    22: "Further application of wisdom and insight.",
    23: "Insight leading to clear comprehension.",
    24: "Wise application integrated into one's way of life.",
    25: "Insight shaping strength and purity.",
    26: "Wise application fostering balance and fairness.",
    27: "Wise recognition of the divine presence within self.",
    28: "Insight aiding the creation of positivity and removal of negativity.",
    29: "Wise application leading to the realization of potential.",
    30: "Insight in the state of wholeness.",
    31: "Clear comprehension enhancing awareness.",
};

export const supremeExplanations: { [key: number]: string } = {
    1: "Knowledge is the foundation of all things in existence. It represents awareness, learning, and perception, allowing us to understand the world around us. By seeking knowledge, we empower ourselves to make informed decisions and grow intellectually.",
    2: "Wisdom is the practical application of knowledge. It involves using one's learned experiences and insights to make sound decisions and to communicate effectively with others. Wisdom is cultivated through experience, reflection, and the application of knowledge in real-world scenarios.",
    3: "Understanding is the deep comprehension and internalization of knowledge and wisdom. It represents the ability to see things clearly and to grasp the interconnectedness of different concepts and ideas. Understanding allows individuals to make sense of the information they have acquired and to perceive the underlying principles that govern the universe.",
    4: "Culture represents the shared values, beliefs, practices, and customs that define a community or an individual. It is the expression of one's identity and heritage. Freedom, in this context, is the ability to live according to one's cultural values and principles without oppression.",
    5: "Power represents the ability to influence and effect change, both within oneself and in the external world. It is the strength to overcome challenges and to assert one's will. Refinement, on the other hand, is the process of purifying and improving oneself.",
    6: "Equality is the principle of treating all individuals with fairness and respect. It emphasizes the importance of maintaining balance and harmony in interactions with others. Equality seeks to eliminate discrimination and to ensure that everyone has equal opportunities to succeed and thrive.",
    7: "God represents the recognition of the divine spark within each individual. It acknowledges that every person has the potential for greatness and the ability to shape their own destiny. By understanding our divine nature, we connect with our true purpose and potential.",
    8: "Build/Destroy represents the dual processes of creation and destruction. Building involves constructing and nurturing positive aspects of life, such as relationships, knowledge, and community. Destroying involves eliminating negative elements that hinder growth and progress.",
    9: "Born signifies the process of bringing ideas, dreams, and goals to fruition. It represents the culmination of effort and the realization of one's potential. Born is about manifesting one's true self and actualizing one's purpose in life.",
    10: "Cipher represents the concept of a complete cycle or circle, symbolizing wholeness and infinity. It is the state of being complete and interconnected, where all parts come together to form a unified whole. Cipher is about understanding the continuous cycles of life, death, and rebirth.",
    11: "Knowledge Knowledge further emphasizes the importance of awareness, learning, and perception. It encourages the pursuit of knowledge for its own sake and the continuous expansion of one's understanding.",
    12: "Knowledge Wisdom represents the combined effort of learning and wise application. It highlights the importance of using our knowledge to make informed and intelligent decisions.",
    13: "Knowledge Understanding emphasizes awareness leading to clear comprehension. It encourages us to seek knowledge not just for information but for deeper understanding and insight.",
    14: "Knowledge Culture/Freedom integrates awareness into one's way of life. It emphasizes the importance of applying our knowledge to enrich our cultural practices and to strive for personal and collective freedom.",
    15: "Knowledge Power/Refinement highlights the role of awareness in shaping strength and purity. It encourages us to use our knowledge to refine our character and to build our inner and outer strength.",
    16: "Knowledge Equality fosters awareness that promotes balance and fairness. It emphasizes the need to understand and address issues of inequality and to work towards creating a just and harmonious society.",
    17: "Knowledge God emphasizes awareness of the divine presence within oneself. It encourages us to recognize our higher potential and to connect with our true purpose.",
    18: "Knowledge Build/Destroy highlights the role of awareness in the creation of positivity and the removal of negativity. It encourages us to use our knowledge to build positive aspects of our lives and to dismantle what no longer serves us.",
    19: "Knowledge Born represents awareness leading to the realization of potential. It emphasizes the importance of using our knowledge to bring our ideas and goals to fruition.",
    20: "Knowledge Cipher signifies awareness in the state of wholeness. It reminds us of the interconnectedness of all things and the continuous cycles of life, death, and rebirth.",
    21: "Wisdom Knowledge represents the practical application of learned knowledge. It emphasizes the importance of using our wisdom to make informed decisions and to navigate life's challenges.",
    22: "Wisdom Wisdom further emphasizes the application of wisdom and insight. It encourages continuous reflection and the refinement of our judgment and decision-making skills.",
    23: "Wisdom Understanding highlights the role of insight in leading to clear comprehension. It encourages us to use our wisdom to gain a deeper understanding of the world and ourselves.",
    24: "Wisdom Culture/Freedom integrates wise application into one's way of life. It emphasizes the importance of using our wisdom to enrich our cultural practices and to strive for personal and collective freedom.",
    25: "Wisdom Power/Refinement highlights the role of insight in shaping strength and purity. It encourages us to use our wisdom to refine our character and to build our inner and outer strength.",
    26: "Wisdom Equality fosters wise application that promotes balance and fairness. It emphasizes the need to use our wisdom to address issues of inequality and to work towards creating a just and harmonious society.",
    27: "Wisdom God emphasizes wise recognition of the divine presence within oneself. It encourages us to recognize our higher potential and to connect with our true purpose.",
    28: "Wisdom Build/Destroy highlights the role of insight in aiding the creation of positivity and the removal of negativity. It encourages us to use our wisdom to build positive aspects of our lives and to dismantle what no longer serves us.",
    29: "Wisdom Born represents wise application leading to the realization of potential. It emphasizes the importance of using our wisdom to bring our ideas and goals to fruition.",
    30: "Wisdom Cipher signifies insight in the state of wholeness. It reminds us of the interconnectedness of all things and the continuous cycles of life, death, and rebirth. Wisdom Cipher encourages individuals to use their wisdom to understand the broader context of existence and to recognize the infinite nature of the universe. It highlights the importance of seeing beyond immediate circumstances and understanding the long-term impacts of our actions. This principle also emphasizes the role of wisdom in maintaining balance and harmony within the endless cycles of life.",
    31: "Understanding Knowledge represents clear comprehension that enhances awareness. It encourages individuals to seek a deeper understanding of the world and to use that understanding to expand their knowledge. This principle highlights the importance of continuous learning and intellectual growth. By gaining a thorough understanding of concepts and ideas, individuals can make more informed decisions and contribute to their personal and communal development. Understanding Knowledge fosters a mindset of curiosity and lifelong learning, promoting the pursuit of wisdom and enlightenment.",
};

